#!/bin/sh
# Prevent repeated starts
PID=$$
readonly TMP_PATH=/tmp/${PID}
readonly LOCK=/var/lock/adblock.lock
if [ -f $LOCK ]; then
    case $1 in
    gen | addown) X=1 ;;
    *) exit 1 ;;
    esac
fi
touch $LOCK

B="Download Subscribe Rules"
FMT_DATE="date +'%Y-%m-%d %H:%M:%S'"
_3RD_URL="$(uci -q get adblock.@adblock[0].url)"
AD_WORK_PATH=/tmp/adblock
W="$(cat /etc/adblock/white.list)"

gen() {
    grep -e "^||[^*]*^$" /tmp/adnew.conf | grep -Ev "^\|\|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}*" | sed -e 's:||:address=/:' -e 's:\^:/:' >/tmp/ad.conf
    for i in $W; do sed -i -e "/\/$i\//d" -e "/\.$i\//d" /tmp/ad.conf; done
    rm -f /tmp/adnew.conf
}

down() {
    tmp_add=/tmp/ad_tmp/3rd
    tmp_ad_new=$tmp_add/ad_new.conf
    rm -rf ${tmp_add%/*}
    mkdir -p $tmp_add
    COUNT_URL=0
    for url in $_3RD_URL; do
        times=1
        while ! uclient-fetch --no-check-certificate --timeout=5 --continue --quiet -O $tmp_ad_new "$url"; do
            [ $times -ge 20 ] && echo "$(eval "$FMT_DATE") [Download $url Failed]" && continue 2 || let times++
            sleep 2
        done
        X=$(md5sum $tmp_add/3rd.conf 2>/dev/null | awk '{print$1}')
        Y=$(md5sum $tmp_add/host 2>/dev/null | awk '{print$1}')
        sed -i 's/\r/\n/g' $tmp_ad_new
        sed -i -e '/127.0.0.1 #/d' -e '/127.0.0.1 !/d' -e 's:#.*::' -e 's:!.*::' -e 's/\$.*//g' -e 's/[ \t]*$//g' -e 's/^[ \t]*//g' -e '/\*/d' -e '/^$/d' $tmp_ad_new
        if grep -q "^address=" $tmp_ad_new; then
            cat $tmp_ad_new >>$tmp_add/3rd.conf
        elif grep -q -e "^0.0.0.0 " -e "^127.0.0.1 " $tmp_ad_new; then
            cat $tmp_ad_new >>$tmp_add/host
        elif ! grep -q -e "|" -e "@" $tmp_ad_new; then
            sed -e 's:^:address=/:' -e 's:$:/:' <$tmp_ad_new >>$tmp_add/3rd.conf
        else
            grep -e "^||[^*]*^$" ${tmp_ad_new} | grep -Ev "^\|\|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}*" | sed -e 's:||:address=/:' -e 's:\^:/:' >>$tmp_add/3rd.conf
        fi
        [ "$X" = "$(md5sum $tmp_add/3rd.conf 2>/dev/null | awk '{print$1}')" -a "$Y" = "$(md5sum $tmp_add/host 2>/dev/null | awk '{print$1}')" ] && echo "$(eval "$FMT_DATE") [Conversion $url Failed]"
        echo "$url" >>$tmp_add/url
        let COUNT_URL++
    done
    [ -s $tmp_add/host ] && sed -e '/:/d' -e '/ 0.0.0.0/d' -e '/255.255.255.255/d' -e '/ local/d' -e 's:127.0.0.1 :address=/:' -e 's:0.0.0.0 :address=/:' -e 's:$:/:' $tmp_add/host >>$tmp_add/3rd.conf
    mkdir -p ${TMP_PATH}
    [ -s $tmp_add/3rd.conf ] && sed -i -e 's:/127.0.0.1$:/:' -e 's:/0.0.0.0$:/:' $tmp_add/3rd.conf && [ "$COUNT_URL" -gt 1 ] && sort -u $tmp_add/3rd.conf >${TMP_PATH}/tmp_3rd && mv ${TMP_PATH}/tmp_3rd $tmp_add/3rd.conf
    [ -s $tmp_add/url ] && sort -u $tmp_add/url >${TMP_PATH}/tmp_url && mv ${TMP_PATH}/tmp_url $tmp_add/url
    rm -rf ${TMP_PATH}

    if [ -s $tmp_add/3rd.conf ]; then
        echo "$(eval "$FMT_DATE") [$B Successful]"
        rm -f $tmp_ad_new $tmp_add/host $AD_WORK_PATH/failed
        for i in $W; do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $tmp_add/3rd.conf; done
        X=$(uci -q get adblock.@adblock[0].flash)
        new_md5=$(md5sum $tmp_add/* | awk '{print$1}')
        [ "$X" = 0 ] && old_md5=$(md5sum $AD_WORK_PATH/3rd/* 2>/dev/null | awk '{print$1}') || old_md5=$(md5sum /etc/adblock/3rd/* 2>/dev/null | awk '{print$1}')
        if [ "$new_md5" != "$old_md5" ]; then
            [ "$1" = 1 ] || echo "$(eval "$FMT_DATE") [Subscribe Rules Need Update]"
            if [ "$X" = 0 ]; then
                rm -f $AD_WORK_PATH/3rd/*
                cp -a $tmp_add "$AD_WORK_PATH"
            else
                rm -f /etc/adblock/3rd/*
                cp -a $tmp_add /etc/adblock
            fi
        else
            echo "$(eval "$FMT_DATE") [Subscribe Rules No Change]"
        fi
    else
        echo "$(eval "$FMT_DATE") [$B Failed]"
        echo failed >$AD_WORK_PATH/failed
        [ "$1" = 2 ] && rm -f $LOCK && exit
    fi
    [ "$1" = 2 ] && rm -f $LOCK && exit
    rm -rf ${tmp_add%/*}
}

case $1 in
addown)
    down 1
    exit
    ;;
down) down 2 ;;
gen)
    gen
    [ "$X" = 1 ] || rm -f $LOCK
    exit
    ;;
esac

if [ "$(uci -q get adblock.@adblock[0].enable)" = 1 ]; then
    [ -n "$_3RD_URL" ] && down
    echo "$(eval "$FMT_DATE")" >$AD_WORK_PATH/adblock.updated
fi

rm -f $LOCK
